baseURL = '/rauchfrei-deinweg/'
languageCode = 'de-de'
title = 'Rauchfrei - Dein Weg'
theme = 'ananke'

[params]
  description = "Dein Weg in ein rauchfreies Leben"
  featured_image = ""
  custom_css = ["custom.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "Startseite"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Für Unternehmen"
  url = "/unternehmen/"
  weight = 2
